packages:
  - 'apps/**'
  - 'packages/**'
  - 'tooling/**'

catalog:
  # Tooling
  'eslint': ^9.28.0
  'prettier': ^3.5.3
  'typescript': ^5.8.3
  'jest': ^29.7.0
  'ts-jest': ^29.3.4
  '@types/jest': ^29.5.14

  # Tanstack & tRPC
  '@tanstack/react-query': ^5.69.0
  '@trpc/client': ^11.1.0
  '@trpc/react-query': ^11.1.0
  '@trpc/server': ^11.1.0

  # Misc
  'superjson': ^2.2.2
  '@t3-oss/env-core': ^0.13.6
  'dotenv-cli': ^8.0.0
  'npm-run-all': '^4.1.5'
  'zod': ^3.25.0
