version: '3'

services:
  db:
    image: postgres:16.2-alpine
    restart: unless-stopped
    networks:
      - app_network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_MULTIPLE_DATABASES: 'splitter_dev, splitter_auth_dev'
    volumes:
      - 'dbdata:/var/lib/postgresql/data/pgdata'
      - './create-multiple-databases.sh:/docker-entrypoint-initdb.d/create-multiple-databases.sh'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'splitter_dev']
      interval: 5s
      timeout: 5s
      retries: 5

  supertokens:
    depends_on:
      db:
        condition: service_healthy
    image: registry.supertokens.io/supertokens/supertokens-postgresql:9.0.2
    restart: unless-stopped
    networks:
      - app_network
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_TABLE_NAMES_PREFIX: splitter_auth
      POSTGRESQL_CONNECTION_URI: 'postgresql://postgres:postgres@db:5432/splitter_auth_dev'

volumes:
  dbdata:

networks:
  app_network:
    driver: bridge
