version: '3'

services:
  db:
    image: postgres:12.4-alpine
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: splitter_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - 'dbdata:/var/lib/postgresql/data/pgdata'

volumes:
  dbdata:
