name: Development - Native Release

on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform to build for (all/android/ios)
        type: choice
        required: true
        default: all
        options:
          - all
          - android
          - ios

jobs:
  native-release-mobile:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: 🏗 Setup repository
        uses: actions/checkout@v3

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Build packages for mobile
        run: pnpm run build:mobile

      - name: 🚀 Build for mobile
        working-directory: apps/mobile
        run: eas build --non-interactive --wait --platform=${{ github.event.inputs.platform }} --profile=development
