name: Preview

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mobile:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repository
        uses: actions/checkout@v3

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Build packages for mobile
        run: pnpm run build:mobile

      - name: 🚀 Publish update for mobile
        working-directory: apps/mobile
        run: eas update --non-interactive --channel=development --message=pr-${{ github.event.number }}

      - name: 💬 Comment update for mobile
        uses: expo/expo-github-action/preview-comment@v7
        with:
          project: apps/mobile
          channel: development
