name: Release

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mobile:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repository
        uses: actions/checkout@v3

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Build packages
        run: yarn build

      - name: 🚀 Publish update
        working-directory: apps/mobile
        run: eas update --non-interactive --channel=production --message=release-${{ github.sha }}

  api:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repository
        uses: actions/checkout@v3

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: 📦 Build packages
        run: yarn build

      - name: 🚀 Publish
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
