name: Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repository
        uses: actions/checkout@v3

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: 🏗 Find current PR Number
        uses: jwalton/gh-find-current-pr@v1
        id: find-current-pr-number

      - name: ✅ Lint packages
        run: yarn lint

      - name: 📦 Build packages
        run: yarn build

      - name: 🧪 Test packages
        run: yarn test

      - name: 💬 Comment mobile coverage report
        working-directory: apps/mobile
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          prnumber: ${{ steps.find-current-pr-number.outputs.number }}
          package-manager: yarn
          annotations: none
          coverage-file: coverage/coverage-final.json

      - name: 💬 Comment api coverage report
        working-directory: apps/mobile
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          prnumber: ${{ steps.find-current-pr-number.outputs.number }}
          package-manager: yarn
          annotations: none
          coverage-file: coverage/coverage-final.json
